version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=local
    volumes:
      - .:/code
      - /code/node_modules
    depends_on:
      - redis
  redis:
    image: redis:alpine
